version: "3"
services:
  db:
    build: ./db
    # image: tyaa/postgres
    restart: always
    ports:
      - "7777:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  web:
    build: ./web
    # image: tyaa/node-app:1.0
    ports:
      - "4000:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: 1
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "app.js"]